In [2]:
import pandas as pd
loan=pd.read_csv("Loan Dataset.csv")
loan.head()

,Applicant_ID,Gender,Age,Marital_Status,Dependents,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,...,Loan_Amount_Requested,Loan_Term,Loan_Purpose,Interest_Rate,Loan_Type,Co-Applicant,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
0,1,Female,25,Married,2,Graduate,Employed,Business,Own,Urban,...,24535,209,Home,4.27,Secured,Yes,8,20,0.81,1
1,2,Male,36,Married,2,High School,Employed,Business,Own,Suburban,...,8288,33,Home,14.78,Unsecured,Yes,9,9,0.17,0
2,3,Male,43,Single,0,Postgraduate,Self-Employed,Freelancer,Own,Urban,...,10308,159,Vehicle,12.33,Secured,Yes,7,27,0.25,0
3,4,Female,28,Married,0,High School,Self-Employed,Freelancer,Rent,Suburban,...,33937,39,Personal,8.77,Secured,No,9,16,0.27,1
4,5,Female,32,Single,0,Graduate,Employed,Salaried,Rent,Suburban,...,23360,34,Home,9.04,Unsecured,No,1,17,0.32,1

In [3]:
loan.shape

(52000, 27)

In [4]:
loan.columns

Index(['Applicant_ID', 'Gender', 'Age', 'Marital_Status', 'Dependents',
       'Education', 'Employment_Status', 'Occupation_Type',
       'Residential_Status', 'City/Town', 'Annual_Income', 'Monthly_Expenses',
       'Credit_Score', 'Existing_Loans', 'Total_Existing_Loan_Amount',
       'Outstanding_Debt', 'Loan_History', 'Loan_Amount_Requested',
       'Loan_Term', 'Loan_Purpose', 'Interest_Rate', 'Loan_Type',
       'Co-Applicant', 'Bank_Account_History', 'Transaction_Frequency',
       'Default_Risk', 'Loan_Approval_Status'],
      dtype='object')

In [5]:
loan.dtypes

Applicant_ID                    int64
Gender                         object
Age                             int64
Marital_Status                 object
Dependents                      int64
Education                      object
Employment_Status              object
Occupation_Type                object
Residential_Status             object
City/Town                      object
Annual_Income                   int64
Monthly_Expenses                int64
Credit_Score                    int64
Existing_Loans                  int64
Total_Existing_Loan_Amount      int64
Outstanding_Debt                int64
Loan_History                    int64
Loan_Amount_Requested           int64
Loan_Term                       int64
Loan_Purpose                   object
Interest_Rate                 float64
Loan_Type                      object
Co-Applicant                   object
Bank_Account_History            int64
Transaction_Frequency           int64
Default_Risk                  float64
Loan_Approval_Status            int64
dtype: object

In [6]:
loan.isnull().sum()

Applicant_ID                  0
Gender                        0
Age                           0
Marital_Status                0
Dependents                    0
Education                     0
Employment_Status             0
Occupation_Type               0
Residential_Status            0
City/Town                     0
Annual_Income                 0
Monthly_Expenses              0
Credit_Score                  0
Existing_Loans                0
Total_Existing_Loan_Amount    0
Outstanding_Debt              0
Loan_History                  0
Loan_Amount_Requested         0
Loan_Term                     0
Loan_Purpose                  0
Interest_Rate                 0
Loan_Type                     0
Co-Applicant                  0
Bank_Account_History          0
Transaction_Frequency         0
Default_Risk                  0
Loan_Approval_Status          0
dtype: int64

In [7]:
loan.duplicated().sum()

np.int64(0)

In [8]:
loan['Applicant_ID'].nunique()

52000

In [9]:
loan.describe()

,Applicant_ID,Age,Dependents,Annual_Income,Monthly_Expenses,Credit_Score,Existing_Loans,Total_Existing_Loan_Amount,Outstanding_Debt,Loan_History,Loan_Amount_Requested,Loan_Term,Interest_Rate,Bank_Account_History,Transaction_Frequency,Default_Risk,Loan_Approval_Status
count,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000,52000.000000
mean,26000.500000,38.898385,1.498000,83588.474404,2748.064885,678.089019,0.997865,24939.087962,14984.864923,0.198596,21102.765481,125.827019,9.253494,4.503923,17.031808,0.500204,0.641654
std,15011.251336,10.553928,1.118077,35720.851522,1295.678763,159.990367,0.815586,14407.886552,8663.404305,0.398947,8224.940906,65.509959,3.318356,2.872721,7.212011,0.289939,0.479519
min,1.000000,18.000000,0.000000,20009.000000,500.000000,300.000000,0.000000,0.000000,0.000000,0.000000,5000.000000,12.000000,3.500000,0.000000,5.000000,0.000000,0.000000
25%,13000.750000,31.000000,0.000000,55564.000000,1636.000000,553.000000,0.000000,12498.000000,7511.750000,0.000000,16941.750000,69.000000,6.400000,2.000000,11.000000,0.250000,0.000000
50%,26000.500000,38.000000,1.000000,78839.000000,2739.000000,742.000000,1.000000,24964.000000,14984.500000,0.000000,21039.000000,126.000000,9.240000,5.000000,17.000000,0.500000,1.000000
75%,39000.250000,45.000000,2.000000,114226.000000,3866.000000,796.000000,2.000000,37399.500000,22432.250000,0.000000,25809.000000,182.000000,12.140000,7.000000,23.000000,0.750000,1.000000
max,52000.000000,69.000000,3.000000,149998.000000,4999.000000,849.000000,2.000000,49999.000000,29998.000000,1.000000,44848.000000,239.000000,15.000000,9.000000,29.000000,1.000000,1.000000

In [10]:
loan.describe(include='object')

,Gender,Marital_Status,Education,Employment_Status,Occupation_Type,Residential_Status,City/Town,Loan_Purpose,Loan_Type,Co-Applicant
count,52000,52000,52000,52000,52000,52000,52000,52000,52000,52000
unique,2,3,3,3,4,3,3,4,2,2
top,Male,Married,Graduate,Employed,Professional,Own,Urban,Home,Secured,No
freq,26011,25957,20787,25871,13191,31178,31188,20919,26097,26036

In [11]:
loan.columns = loan.columns.str.replace('/', '_')
loan.columns

Index(['Applicant_ID', 'Gender', 'Age', 'Marital_Status', 'Dependents',
       'Education', 'Employment_Status', 'Occupation_Type',
       'Residential_Status', 'City_Town', 'Annual_Income', 'Monthly_Expenses',
       'Credit_Score', 'Existing_Loans', 'Total_Existing_Loan_Amount',
       'Outstanding_Debt', 'Loan_History', 'Loan_Amount_Requested',
       'Loan_Term', 'Loan_Purpose', 'Interest_Rate', 'Loan_Type',
       'Co-Applicant', 'Bank_Account_History', 'Transaction_Frequency',
       'Default_Risk', 'Loan_Approval_Status'],
      dtype='object')

In [12]:
loan['Loan_Approval_Status'].value_counts()

Loan_Approval_Status
1    33366
0    18634
Name: count, dtype: int64

In [13]:
loan['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
1    64.165385
0    35.834615
Name: proportion, dtype: float64

In [14]:
loan[loan['Credit_Score'] < 600]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
0    85.020688
1    14.979312
Name: proportion, dtype: float64

In [15]:
loan[loan['Credit_Score'] >= 600]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
1    84.991241
0    15.008759
Name: proportion, dtype: float64

In [16]:
loan[loan['Age'] > 50]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
0    84.861483
1    15.138517
Name: proportion, dtype: float64

In [17]:
loan[loan['Age'] <= 50]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
1    70.0765
0    29.9235
Name: proportion, dtype: float64

In [18]:
loan[(loan['Credit_Score'] >= 600) & (loan['Age'] <= 50)]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
1    84.991241
0    15.008759
Name: proportion, dtype: float64

In [19]:
features = ['Gender', 'Marital_Status', 'Education', 'Employment_Status', 'Residential_Status', 'City_Town', 'Loan_Purpose', 'Loan_Type']

for col in features:
    display(loan.groupby(col)['Loan_Approval_Status'].value_counts(normalize=True) * 100)

Gender  Loan_Approval_Status
Female  1                       64.365693
        0                       35.634307
Male    1                       63.965245
        0                       36.034755
Name: proportion, dtype: float64

Marital_Status  Loan_Approval_Status
Divorced        1                       63.394216
                0                       36.605784
Married         1                       64.514389
                0                       35.485611
Single          1                       63.924568
                0                       36.075432
Name: proportion, dtype: float64

Education     Loan_Approval_Status
Graduate      1                       64.083321
              0                       35.916679
High School   1                       64.336270
              0                       35.663730
Postgraduate  1                       63.988893
              0                       36.011107
Name: proportion, dtype: float64

Employment_Status  Loan_Approval_Status
Employed           1                       64.110394
                   0                       35.889606
Self-Employed      1                       64.927315
                   0                       35.072685
Unemployed         1                       63.145721
                   0                       36.854279
Name: proportion, dtype: float64

Residential_Status  Loan_Approval_Status
Other               1                       63.813527
                    0                       36.186473
Own                 1                       64.433254
                    0                       35.566746
Rent                1                       63.747755
                    0                       36.252245
Name: proportion, dtype: float64

City_Town  Loan_Approval_Status
Rural      1                       63.746398
           0                       36.253602
Suburban   1                       64.688922
           0                       35.311078
Urban      1                       63.973323
           0                       36.026677
Name: proportion, dtype: float64

Loan_Purpose  Loan_Approval_Status
Education     1                       63.737432
              0                       36.262568
Home          1                       63.889287
              0                       36.110713
Personal      1                       64.797688
              0                       35.202312
Vehicle       1                       64.516752
              0                       35.483248
Name: proportion, dtype: float64

Loan_Type  Loan_Approval_Status
Secured    1                       64.202782
           0                       35.797218
Unsecured  1                       64.127707
           0                       35.872293
Name: proportion, dtype: float64

In [20]:
loan.groupby('Loan_Approval_Status')['Loan_Amount_Requested'].mean()

Loan_Approval_Status
0    15515.996565
1    24222.823383
Name: Loan_Amount_Requested, dtype: float64

In [21]:
loan[(loan['Credit_Score'] >= 600) & (loan['Age'] <= 50)]['Loan_Approval_Status'].value_counts(normalize=True) * 100

Loan_Approval_Status
1    84.991241
0    15.008759
Name: proportion, dtype: float64

In [22]:
loan.groupby('Loan_Approval_Status')[['Annual_Income', 'Outstanding_Debt', 'Default_Risk']].mean()

                      Annual_Income  Outstanding_Debt  Default_Risk
Loan_Approval_Status
0                      61020.549587      15019.204680      0.502186
1                      96192.044237      14965.687107      0.499097

In [23]:
loan.to_csv('cleaned_loan_approval.csv', index=False)

In [24]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\acer\appdata\local\programs\python\python310\lib\site-packages (1.2.0)

In [27]:
from sqlalchemy import create_engine

engine = create_engine('mysql+pymysql://root:@localhost:3306/loan_db')

loan.to_sql('loans', con=engine, if_exists='replace', index=False)
print("success")

success

In [1]:
import os
print(os.path.abspath('cleaned_loan_approval.csv'))

C:\Users\acer\cleaned_loan_approval.csv